"""Generates `language-reference.md` from the docstrings of the `tl` builtins.

Run it from the repository root after you change a builtin or its docstring:

    uv run python docs/guide/gen_reference.py

With `--check`, the script writes nothing and exits with status 1 if the committed
reference differs from the generated one. `tests/test_docs.py` runs the same check.
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

import enceladus.language as tl
from enceladus.language.core import DESC_METHODS, TILE_METHODS, Builtin

OUTPUT = Path(__file__).with_name("language-reference.md")

# (heading, introduction, builtin names). Every exported builtin must appear exactly once;
# `generate` raises an error for a builtin that no section lists.
SECTIONS: list[tuple[str, str, list[str]]] = [
    ("Programs", "These functions describe the current program and the launch grid.",
     ["program_id", "num_programs"]),
    ("Tile creation", "These functions create tiles. Shapes hold compile-time powers of two.",
     ["arange", "full", "zeros", "full_like", "zeros_like"]),
    ("Memory", "These functions read and write device memory through pointers.",
     ["load", "store"]),
    ("Tensor descriptors",
     "Tensor descriptors carry a shape and strides, so block loads and stores check their "
     "own bounds.",
     ["make_tensor_descriptor"]),
    ("Elementwise arithmetic",
     "These functions work elementwise and broadcast their arguments to one shape.",
     ["where", "maximum", "minimum", "clamp", "fma", "abs", "cdiv"]),
    ("Math functions",
     "These functions need floating-point inputs. `float16` and `bfloat16` inputs compute "
     "in `float32` and round the result back.",
     ["exp", "exp2", "log", "log2", "sqrt", "rsqrt", "sin", "cos", "tanh", "sigmoid", "erf",
      "floor", "ceil"]),
    ("Type conversion", "This function converts or reinterprets element types.", ["cast"]),
    ("Shape manipulation", "These functions change the shape of a tile without computing.",
     ["broadcast_to", "expand_dims", "reshape", "trans", "permute"]),
    ("Reductions", "These functions reduce a tile along an axis.",
     ["sum", "max", "min", "argmax", "argmin", "reduce"]),
    ("Scans", "These functions compute inclusive prefix scans along an axis.",
     ["cumsum", "associative_scan"]),
    ("Matrix multiplication", "This function multiplies two 2D tiles.", ["dot"]),
    ("Atomics",
     "These functions update device memory atomically and return the previous values.",
     ["atomic_add", "atomic_max", "atomic_min", "atomic_xchg", "atomic_and", "atomic_or",
      "atomic_xor", "atomic_cas"]),
    ("Loops and compile-time helpers",
     "These functions control loops and run checks while the kernel compiles.",
     ["range", "static_range", "static_assert", "static_print"]),
    ("Debugging", "These functions help you debug kernels on the GPU.",
     ["device_print", "device_assert"]),
]  # fmt: skip

HEADER = """\
# Language reference

<!-- Generated by docs/guide/gen_reference.py from the builtin docstrings. Don't edit
this file by hand; edit the docstrings in src/enceladus/language/ and rerun the script. -->

This page lists every function in the `enceladus.language` namespace, which you import as
`tl`:

```python
import enceladus.language as tl
```

The functions run only inside a `@enceladus.jit` function. For the concepts behind them,
see [Programming model](programming-model.md).

## Data types

The following element types are available as `tl` attributes. Enceladus has no 64-bit
floating-point type.

| Type | Kind | Bits |
|---|---|---|
{dtype_rows}

## Tile attributes and methods

A tile `x` has the following attributes:

- `x.shape`: the shape, as a tuple of ints.
- `x.dtype`: the element type. For a pointer, it's the pointee type, so both
  `x_ptr.dtype` and `x_ptr.dtype.element_ty` give the element type.
- `x.numel`: the number of elements.
- `x.T`: the transpose, as `tl.trans(x)`.

You can also call the following functions as methods of a tile, for example
`x.sum(axis=0)` or `x.to(tl.float16)`:

{methods}

Tiles support the operators `+`, `-`, `*`, `/`, `//`, `%`, `&`, `|`, `^`, `~`, `<<`,
`>>`, and the comparisons. `**` and `@` aren't supported on runtime values; use
`tl.dot` for matrix products. Indexing with `None` and `:` inserts dimensions, for
example `x[:, None]`.

## Tensor descriptor methods

A tensor descriptor `desc` from `tl.make_tensor_descriptor` has the following methods:

{desc_methods}
"""


def _signature(name: str, b: Builtin) -> str:
    sig = inspect.signature(b.frontend)
    params = list(sig.parameters.values())
    if params and params[0].name == "ctx":
        params = params[1:]
    text = str(sig.replace(parameters=params))
    if text == "(*args, **kwargs)":  # loop ranges accept Python's range arguments
        text = "(start, end=None, step=None)" if name == "static_range" else (
            "(start, end=None, step=None, num_stages=None, loop_unroll_factor=None, "
            "disallow_acc_multi_buffer=False, flatten=False, warp_specialize=False)")
    return f"tl.{name}{text}"


def _doc(b: Builtin) -> str:
    doc = inspect.cleandoc(b.__doc__ or "")
    if not doc:
        raise ValueError(f"tl.{b.name} has no docstring")
    return doc


def _method_names(b: Builtin) -> list[str]:
    return sorted(m for m, v in TILE_METHODS.items() if v is b and m != b.name) + (
        [b.name] if TILE_METHODS.get(b.name) is b else [])


def generate() -> str:
    """Returns the reference page as Markdown text."""
    exported = {n: getattr(tl, n) for n in tl.__all__ if isinstance(getattr(tl, n), Builtin)}
    listed = [n for _, _, names in SECTIONS for n in names]
    missing = sorted(set(exported) - set(listed))
    extra = sorted(set(listed) - set(exported))
    if missing or extra or len(listed) != len(set(listed)):
        raise ValueError(f"SECTIONS is out of date: missing {missing}, unknown {extra}")

    dtypes = [getattr(tl, n) for n in ("int1", "int8", "int16", "int32", "int64", "uint8",
                                       "uint16", "uint32", "uint64", "float16", "bfloat16",
                                       "float32")]  # fmt: skip
    dtype_rows = "\n".join(f"| `tl.{d.long_name}` | {d.kind} | {d.primitive_bitwidth} |"
                           for d in dtypes)  # fmt: skip
    methods = sorted(m for m in TILE_METHODS if m != "to") + ["to"]
    method_lines = []
    for m in methods:
        b = TILE_METHODS[m]
        target = "`tl.cast`" if m == "to" else f"`tl.{b.name}`"
        method_lines.append(f"- `x.{m}(...)`: {target}")
    desc_lines = [
        f"- `desc.{m}{_desc_sig(m)}`: {_doc(DESC_METHODS[m]).splitlines()[0]}"
        for m in sorted(DESC_METHODS)
    ]
    out = [HEADER.format(dtype_rows=dtype_rows, methods="\n".join(method_lines),
                         desc_methods="\n".join(desc_lines))]  # fmt: skip
    for heading, intro, names in SECTIONS:
        out.append(f"## {heading}\n\n{intro}\n")
        for n in names:
            b = exported[n]
            out.append(f"### `tl.{n}`\n\n**Signature:** `{_signature(n, b)}`\n\n{_doc(b)}\n")
            meths = _method_names(b)
            if meths:
                calls = ", ".join(f"`x.{m}(...)`" for m in meths)
                out.append(f"You can also call it as a tile method: {calls}.\n")
    return "\n".join(out).rstrip() + "\n"


def _desc_sig(method: str) -> str:
    return "(offsets)" if method == "load" else "(offsets, value)"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit with status 1 if the committed reference is out of date")
    args = parser.parse_args(argv)
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            print(f"{OUTPUT} is out of date; run `uv run python docs/guide/gen_reference.py`",
                  file=sys.stderr)  # fmt: skip
            return 1
        return 0
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
